language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: stable
  fast_finish: true
notifications:
  email:
    on_success: never
    on_failure: never
  