language: rust
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: stable
  fast_finish: true
install:
  - cargo build
script:
  - cargo build; cargo test
notifications:
  email:
    on_success: never
    on_failure: never
  